# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import roadmap_pb2 as roadmap__pb2
from . import scenario_pb2 as scenario__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature.proto',
  package='feature',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rfeature.proto\x12\x07\x66\x65\x61ture\x1a\x0c\x63ommon.proto\x1a\rroadmap.proto\x1a\x0escenario.proto\"\xec\x01\n\x14MotorJunctionFeature\x12#\n\x08junction\x18\x01 \x01(\x0b\x32\x11.roadmap.Junction\x12\x1f\n\tobj_entry\x18\x02 \x01(\x0b\x32\x0c.common.Pose\x12#\n\x1bmotor_veh_dbn_cont_evidence\x18\x03 \x03(\x02\x12%\n\x1dmotor_veh_dbn_causal_evidence\x18\x04 \x03(\x08\x12\x1f\n\x17\x64\x62n_cont_evidence_valid\x18\x05 \x03(\x08\x12!\n\x19\x64\x62n_causal_evidence_valid\x18\x06 \x03(\x08\"\xa8\x01\n\x07\x46\x65\x61ture\x12\x0e\n\x06obj_id\x18\x01 \x01(\x05\x12\x1e\n\x08obj_pose\x18\x02 \x01(\x0b\x32\x0c.common.Pose\x12.\n\x08scenario\x18\x03 \x03(\x0e\x32\x1c.scenario.PredictionScenario\x12=\n\x16motor_junction_feature\x18\x04 \x01(\x0b\x32\x1d.feature.MotorJunctionFeature\"A\n\x08\x46\x65\x61tures\x12\x11\n\tframe_idx\x18\x01 \x01(\x05\x12\"\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x10.feature.Feature*\xb1\x01\n\x1cMotorJunctionDBNContEvidence\x12\x0e\n\nLANE_THETA\x10\x00\x12!\n\x1dRATIO_LANE_DIST_TO_LANE_WIDTH\x10\x01\x12\x1e\n\x1aRATIO_LNG_DIST_TO_MOV_DIST\x10\x02\x12\x14\n\x10RATIO_V_TO_V_MAX\x10\x03\x12(\n$MOTOR_JUNCTION_DBN_CONT_EVIDENCE_NUM\x10\x04*\x93\x01\n\x1eMotorJunctionDBNCausalEvidence\x12\x15\n\x11NEAR_LANE_TO_EXIT\x10\x00\x12\x16\n\x12THETA_WITHIN_RANGE\x10\x01\x12\x16\n\x12REVERSE_LANE_THETA\x10\x02\x12*\n&MOTOR_JUNCTION_DBN_CAUSAL_EVIDENCE_NUM\x10\x03\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,roadmap__pb2.DESCRIPTOR,scenario__pb2.DESCRIPTOR,])

_MOTORJUNCTIONDBNCONTEVIDENCE = _descriptor.EnumDescriptor(
  name='MotorJunctionDBNContEvidence',
  full_name='feature.MotorJunctionDBNContEvidence',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LANE_THETA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RATIO_LANE_DIST_TO_LANE_WIDTH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RATIO_LNG_DIST_TO_MOV_DIST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RATIO_V_TO_V_MAX', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_JUNCTION_DBN_CONT_EVIDENCE_NUM', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=549,
  serialized_end=726,
)
_sym_db.RegisterEnumDescriptor(_MOTORJUNCTIONDBNCONTEVIDENCE)

MotorJunctionDBNContEvidence = enum_type_wrapper.EnumTypeWrapper(_MOTORJUNCTIONDBNCONTEVIDENCE)
_MOTORJUNCTIONDBNCAUSALEVIDENCE = _descriptor.EnumDescriptor(
  name='MotorJunctionDBNCausalEvidence',
  full_name='feature.MotorJunctionDBNCausalEvidence',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEAR_LANE_TO_EXIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THETA_WITHIN_RANGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVERSE_LANE_THETA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_JUNCTION_DBN_CAUSAL_EVIDENCE_NUM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=729,
  serialized_end=876,
)
_sym_db.RegisterEnumDescriptor(_MOTORJUNCTIONDBNCAUSALEVIDENCE)

MotorJunctionDBNCausalEvidence = enum_type_wrapper.EnumTypeWrapper(_MOTORJUNCTIONDBNCAUSALEVIDENCE)
LANE_THETA = 0
RATIO_LANE_DIST_TO_LANE_WIDTH = 1
RATIO_LNG_DIST_TO_MOV_DIST = 2
RATIO_V_TO_V_MAX = 3
MOTOR_JUNCTION_DBN_CONT_EVIDENCE_NUM = 4
NEAR_LANE_TO_EXIT = 0
THETA_WITHIN_RANGE = 1
REVERSE_LANE_THETA = 2
MOTOR_JUNCTION_DBN_CAUSAL_EVIDENCE_NUM = 3



_MOTORJUNCTIONFEATURE = _descriptor.Descriptor(
  name='MotorJunctionFeature',
  full_name='feature.MotorJunctionFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='junction', full_name='feature.MotorJunctionFeature.junction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obj_entry', full_name='feature.MotorJunctionFeature.obj_entry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_veh_dbn_cont_evidence', full_name='feature.MotorJunctionFeature.motor_veh_dbn_cont_evidence', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_veh_dbn_causal_evidence', full_name='feature.MotorJunctionFeature.motor_veh_dbn_causal_evidence', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbn_cont_evidence_valid', full_name='feature.MotorJunctionFeature.dbn_cont_evidence_valid', index=4,
      number=5, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbn_causal_evidence_valid', full_name='feature.MotorJunctionFeature.dbn_causal_evidence_valid', index=5,
      number=6, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=308,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='feature.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj_id', full_name='feature.Feature.obj_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obj_pose', full_name='feature.Feature.obj_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scenario', full_name='feature.Feature.scenario', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_junction_feature', full_name='feature.Feature.motor_junction_feature', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=479,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='feature.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_idx', full_name='feature.Features.frame_idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='feature.Features.features', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=546,
)

_MOTORJUNCTIONFEATURE.fields_by_name['junction'].message_type = roadmap__pb2._JUNCTION
_MOTORJUNCTIONFEATURE.fields_by_name['obj_entry'].message_type = common__pb2._POSE
_FEATURE.fields_by_name['obj_pose'].message_type = common__pb2._POSE
_FEATURE.fields_by_name['scenario'].enum_type = scenario__pb2._PREDICTIONSCENARIO
_FEATURE.fields_by_name['motor_junction_feature'].message_type = _MOTORJUNCTIONFEATURE
_FEATURES.fields_by_name['features'].message_type = _FEATURE
DESCRIPTOR.message_types_by_name['MotorJunctionFeature'] = _MOTORJUNCTIONFEATURE
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.enum_types_by_name['MotorJunctionDBNContEvidence'] = _MOTORJUNCTIONDBNCONTEVIDENCE
DESCRIPTOR.enum_types_by_name['MotorJunctionDBNCausalEvidence'] = _MOTORJUNCTIONDBNCAUSALEVIDENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorJunctionFeature = _reflection.GeneratedProtocolMessageType('MotorJunctionFeature', (_message.Message,), {
  'DESCRIPTOR' : _MOTORJUNCTIONFEATURE,
  '__module__' : 'feature_pb2'
  # @@protoc_insertion_point(class_scope:feature.MotorJunctionFeature)
  })
_sym_db.RegisterMessage(MotorJunctionFeature)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'feature_pb2'
  # @@protoc_insertion_point(class_scope:feature.Feature)
  })
_sym_db.RegisterMessage(Feature)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), {
  'DESCRIPTOR' : _FEATURES,
  '__module__' : 'feature_pb2'
  # @@protoc_insertion_point(class_scope:feature.Features)
  })
_sym_db.RegisterMessage(Features)


# @@protoc_insertion_point(module_scope)
