# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor_junction_dbn_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor_junction_dbn_model.proto',
  package='motor_junction_dbn_model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1emotor_junction_dbn_model.proto\x12\x18motor_junction_dbn_model\"\xef\x01\n\x15MotorJunctionDBNModel\x12(\n continuous_evidence_interval_num\x18\x01 \x03(\x05\x12\x0c\n\x04ispt\x18\x02 \x03(\x02\x12\x0c\n\x04iert\x18\x03 \x03(\x05\x12\x19\n\x11\x65vidence_interval\x18\x04 \x03(\x02\x12\x0b\n\x03\x63pt\x18\x05 \x03(\x02\x12\x1b\n\x13\x63ontinuous_evidence\x18\x06 \x03(\t\x12\x17\n\x0f\x62inary_evidence\x18\x07 \x03(\t\x12\x17\n\x0f\x63\x61usal_evidence\x18\x08 \x03(\t\x12\x19\n\x11prior_sample_size\x18\t \x01(\x05\x62\x06proto3'
)




_MOTORJUNCTIONDBNMODEL = _descriptor.Descriptor(
  name='MotorJunctionDBNModel',
  full_name='motor_junction_dbn_model.MotorJunctionDBNModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='continuous_evidence_interval_num', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.continuous_evidence_interval_num', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ispt', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.ispt', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iert', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.iert', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evidence_interval', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.evidence_interval', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpt', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.cpt', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='continuous_evidence', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.continuous_evidence', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='binary_evidence', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.binary_evidence', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='causal_evidence', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.causal_evidence', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prior_sample_size', full_name='motor_junction_dbn_model.MotorJunctionDBNModel.prior_sample_size', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=300,
)

DESCRIPTOR.message_types_by_name['MotorJunctionDBNModel'] = _MOTORJUNCTIONDBNMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorJunctionDBNModel = _reflection.GeneratedProtocolMessageType('MotorJunctionDBNModel', (_message.Message,), {
  'DESCRIPTOR' : _MOTORJUNCTIONDBNMODEL,
  '__module__' : 'motor_junction_dbn_model_pb2'
  # @@protoc_insertion_point(class_scope:motor_junction_dbn_model.MotorJunctionDBNModel)
  })
_sym_db.RegisterMessage(MotorJunctionDBNModel)


# @@protoc_insertion_point(module_scope)
