# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roadmap.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='roadmap.proto',
  package='roadmap',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rroadmap.proto\x12\x07roadmap\x1a\x0c\x63ommon.proto\"\x1e\n\x0cLaneInternal\x12\x0e\n\x06id_str\x18\x01 \x01(\t\"J\n\x14LaneSequenceInternal\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12$\n\x05lanes\x18\x02 \x03(\x0b\x32\x15.roadmap.LaneInternal\"\'\n\x04Lane\x12\x0e\n\x06seg_id\x18\x01 \x01(\x05\x12\x0f\n\x07lane_id\x18\x02 \x01(\x05\":\n\x0cLaneSequence\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x1c\n\x05lanes\x18\x02 \x03(\x0b\x32\r.roadmap.Lane\"^\n\x08LaneInfo\x12\x11\n\tnode_size\x18\x01 \x01(\x05\x12\x11\n\tnode_list\x18\x02 \x03(\x05\x12\x1d\n\x08node_pos\x18\x03 \x03(\x0b\x32\x0b.common.Pos\x12\r\n\x05width\x18\x04 \x01(\x02\"J\n\x07Segment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12%\n\nlane_infos\x18\x03 \x03(\x0b\x32\x11.roadmap.LaneInfo\">\n\nSegmentSet\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\"\n\x08segments\x18\x02 \x03(\x0b\x32\x10.roadmap.Segment\"\'\n\x04Node\x12\x0e\n\x06seg_id\x18\x01 \x01(\x05\x12\x0f\n\x07lane_id\x18\x02 \x01(\x05\"5\n\x07Section\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x1c\n\x05nodes\x18\x02 \x03(\x0b\x32\r.roadmap.Node\"9\n\x05Route\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\"\n\x08sections\x18\x02 \x03(\x0b\x32\x10.roadmap.Section\"\x8b\x01\n\x08Junction\x12\x13\n\x0bjunction_id\x18\x01 \x01(\x05\x12%\n\x0fjunction_entrys\x18\x02 \x03(\x0b\x32\x0c.common.Pose\x12$\n\x0ejunction_exits\x18\x03 \x03(\x0b\x32\x0c.common.Pose\x12\x1d\n\x08vertices\x18\x04 \x03(\x0b\x32\x0b.common.Posb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_LANEINTERNAL = _descriptor.Descriptor(
  name='LaneInternal',
  full_name='roadmap.LaneInternal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_str', full_name='roadmap.LaneInternal.id_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=70,
)


_LANESEQUENCEINTERNAL = _descriptor.Descriptor(
  name='LaneSequenceInternal',
  full_name='roadmap.LaneSequenceInternal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.LaneSequenceInternal.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lanes', full_name='roadmap.LaneSequenceInternal.lanes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=146,
)


_LANE = _descriptor.Descriptor(
  name='Lane',
  full_name='roadmap.Lane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seg_id', full_name='roadmap.Lane.seg_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='roadmap.Lane.lane_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=187,
)


_LANESEQUENCE = _descriptor.Descriptor(
  name='LaneSequence',
  full_name='roadmap.LaneSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.LaneSequence.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lanes', full_name='roadmap.LaneSequence.lanes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=247,
)


_LANEINFO = _descriptor.Descriptor(
  name='LaneInfo',
  full_name='roadmap.LaneInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_size', full_name='roadmap.LaneInfo.node_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_list', full_name='roadmap.LaneInfo.node_list', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_pos', full_name='roadmap.LaneInfo.node_pos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='roadmap.LaneInfo.width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=343,
)


_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='roadmap.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='roadmap.Segment.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.Segment.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lane_infos', full_name='roadmap.Segment.lane_infos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=419,
)


_SEGMENTSET = _descriptor.Descriptor(
  name='SegmentSet',
  full_name='roadmap.SegmentSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.SegmentSet.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segments', full_name='roadmap.SegmentSet.segments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=483,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='roadmap.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seg_id', full_name='roadmap.Node.seg_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='roadmap.Node.lane_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=524,
)


_SECTION = _descriptor.Descriptor(
  name='Section',
  full_name='roadmap.Section',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.Section.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='roadmap.Section.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=579,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='roadmap.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='roadmap.Route.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sections', full_name='roadmap.Route.sections', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=638,
)


_JUNCTION = _descriptor.Descriptor(
  name='Junction',
  full_name='roadmap.Junction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='junction_id', full_name='roadmap.Junction.junction_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='junction_entrys', full_name='roadmap.Junction.junction_entrys', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='junction_exits', full_name='roadmap.Junction.junction_exits', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='roadmap.Junction.vertices', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=780,
)

_LANESEQUENCEINTERNAL.fields_by_name['lanes'].message_type = _LANEINTERNAL
_LANESEQUENCE.fields_by_name['lanes'].message_type = _LANE
_LANEINFO.fields_by_name['node_pos'].message_type = common__pb2._POS
_SEGMENT.fields_by_name['lane_infos'].message_type = _LANEINFO
_SEGMENTSET.fields_by_name['segments'].message_type = _SEGMENT
_SECTION.fields_by_name['nodes'].message_type = _NODE
_ROUTE.fields_by_name['sections'].message_type = _SECTION
_JUNCTION.fields_by_name['junction_entrys'].message_type = common__pb2._POSE
_JUNCTION.fields_by_name['junction_exits'].message_type = common__pb2._POSE
_JUNCTION.fields_by_name['vertices'].message_type = common__pb2._POS
DESCRIPTOR.message_types_by_name['LaneInternal'] = _LANEINTERNAL
DESCRIPTOR.message_types_by_name['LaneSequenceInternal'] = _LANESEQUENCEINTERNAL
DESCRIPTOR.message_types_by_name['Lane'] = _LANE
DESCRIPTOR.message_types_by_name['LaneSequence'] = _LANESEQUENCE
DESCRIPTOR.message_types_by_name['LaneInfo'] = _LANEINFO
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.message_types_by_name['SegmentSet'] = _SEGMENTSET
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Section'] = _SECTION
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Junction'] = _JUNCTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneInternal = _reflection.GeneratedProtocolMessageType('LaneInternal', (_message.Message,), {
  'DESCRIPTOR' : _LANEINTERNAL,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.LaneInternal)
  })
_sym_db.RegisterMessage(LaneInternal)

LaneSequenceInternal = _reflection.GeneratedProtocolMessageType('LaneSequenceInternal', (_message.Message,), {
  'DESCRIPTOR' : _LANESEQUENCEINTERNAL,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.LaneSequenceInternal)
  })
_sym_db.RegisterMessage(LaneSequenceInternal)

Lane = _reflection.GeneratedProtocolMessageType('Lane', (_message.Message,), {
  'DESCRIPTOR' : _LANE,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Lane)
  })
_sym_db.RegisterMessage(Lane)

LaneSequence = _reflection.GeneratedProtocolMessageType('LaneSequence', (_message.Message,), {
  'DESCRIPTOR' : _LANESEQUENCE,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.LaneSequence)
  })
_sym_db.RegisterMessage(LaneSequence)

LaneInfo = _reflection.GeneratedProtocolMessageType('LaneInfo', (_message.Message,), {
  'DESCRIPTOR' : _LANEINFO,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.LaneInfo)
  })
_sym_db.RegisterMessage(LaneInfo)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Segment)
  })
_sym_db.RegisterMessage(Segment)

SegmentSet = _reflection.GeneratedProtocolMessageType('SegmentSet', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSET,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.SegmentSet)
  })
_sym_db.RegisterMessage(SegmentSet)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Node)
  })
_sym_db.RegisterMessage(Node)

Section = _reflection.GeneratedProtocolMessageType('Section', (_message.Message,), {
  'DESCRIPTOR' : _SECTION,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Section)
  })
_sym_db.RegisterMessage(Section)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Route)
  })
_sym_db.RegisterMessage(Route)

Junction = _reflection.GeneratedProtocolMessageType('Junction', (_message.Message,), {
  'DESCRIPTOR' : _JUNCTION,
  '__module__' : 'roadmap_pb2'
  # @@protoc_insertion_point(class_scope:roadmap.Junction)
  })
_sym_db.RegisterMessage(Junction)


# @@protoc_insertion_point(module_scope)
