# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scenario.proto',
  package='scenario',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0escenario.proto\x12\x08scenario*\xc8\x01\n\x12PredictionScenario\x12\x19\n\x15INVALID_PRED_SCENARIO\x10\x00\x12\x11\n\rMOTOR_REGULAR\x10\x01\x12\x12\n\x0eMOTOR_JUNCTION\x10\x02\x12\x15\n\x11NON_MOTOR_REGULAR\x10\x03\x12\x16\n\x12NON_MOTOR_JUNCTION\x10\x04\x12\x17\n\x13NON_MOTOR_CROSSWALK\x10\x05\x12\x11\n\rPED_CROSSWALK\x10\x06\x12\x15\n\x11PED_NON_CROSSWALK\x10\x07\x62\x06proto3'
)

_PREDICTIONSCENARIO = _descriptor.EnumDescriptor(
  name='PredictionScenario',
  full_name='scenario.PredictionScenario',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_PRED_SCENARIO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_REGULAR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_JUNCTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NON_MOTOR_REGULAR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NON_MOTOR_JUNCTION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NON_MOTOR_CROSSWALK', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PED_CROSSWALK', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PED_NON_CROSSWALK', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=29,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_PREDICTIONSCENARIO)

PredictionScenario = enum_type_wrapper.EnumTypeWrapper(_PREDICTIONSCENARIO)
INVALID_PRED_SCENARIO = 0
MOTOR_REGULAR = 1
MOTOR_JUNCTION = 2
NON_MOTOR_REGULAR = 3
NON_MOTOR_JUNCTION = 4
NON_MOTOR_CROSSWALK = 5
PED_CROSSWALK = 6
PED_NON_CROSSWALK = 7


DESCRIPTOR.enum_types_by_name['PredictionScenario'] = _PREDICTIONSCENARIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
